version: "3"
services:
  web-nextjs:
    container_name: web-nextjs.localhost
    build:
      context: ./web-nextjs
    environment:
      - "ENCRYPTION_ALGORITHM=aes-256-cbc"
      - "ENCRYPTION_SECRET=this is my secret"
      - "ENCRYPTION_SALT=this is my salt"
      - "GITHUB_AUTH_URL=https://github.com/login/oauth/authorize"
    networks:
      - microservices-net
    depends_on:
      - catalog-csharp
      - api-go

  catalog-csharp:
    container_name: catalog-csharp.localhost
    build:
      context: ./catalog-csharp
    environment:
      - "API_BASE_URL=http://api-go.localhost"
      - "API_BASE_URL_TLS=https://api-go.localhost"
      - "CONNECTION_STRING=Server=catalog-db;Database=CATALOG;User Id=sa; Password=P@ssw0rd;"
    ports:
      - "1433:1433"
    networks:
      - microservices-net
    depends_on:
      - rabbitmq

  api-go:
    container_name: api-go.localhost
    build:
      context: ./api-go
    environment: 
      - "SERVICE_PORT=80"
      - "CATALOG_BASE_URL=http://catalog-csharp.localhost"
      - "IDENTITY_BASE_URL=http://identity-java.localhost"
      - "GITHUB_CLIENT_ID="
      - "GITHUB_SECRET="
      - "GITHUB_TOKEN_URL=https://github.com/login/oauth/access_token"
      - "GITHUB_USER_INFO_URL=https://api.github.com/user?access_token=%s"
    networks: 
      - microservices-net
    depends_on: 
      - catalog-csharp

  eventbus-rabbitmq:
    container_name: eventbus-rabbitmq
    build:
      context: ./eventbus-rabbitmq
    networks:
      - microservices-net

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - microservices-net
    depends_on: 
      - catalog-csharp
      - web-nextjs
      - api-go

networks: 
  microservices-net: 
    driver: bridge