version: "3"
services:
  web-nextjs:
    container_name: web-nextjs
    build:
      context: ./web-nextjs
    networks:
      - microservices-net
    depends_on:
      - catalog-csharp
    
  catalog-csharp:
    container_name: catalog-csharp
    build:
      context: ./catalog-csharp
    networks:
      - microservices-net

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - microservices-net
    depends_on: 
      - catalog-csharp
      - web-nextjs

networks: 
  microservices-net: 
    driver: bridge