version: "3"
services:
  web-nextjs:
    container_name: web-nextjs.localhost
    build:
      context: ./web-nextjs
    environment:
      - "GITHUB_AUTH_URL=https://github.com/login/oauth/authorize?client_id="
      - "REFRESH_TOKEN_LIFE_TIME=6000"
    networks:
      - microservices-net
    depends_on:
      - api-go

  catalog-csharp:
    container_name: catalog-csharp.localhost
    build:
      context: ./catalog-csharp
    environment:
      - "API_BASE_URL=http://api-go.localhost"
      - "API_BASE_URL_TLS=https://api-go.localhost"
      - "CONNECTION_STRING=Server=catalog-db;Database=CATALOG;User Id=sa; Password=P@ssw0rd;"
    ports:
      - "1433:1433"
    networks:
      - microservices-net

  identity-java:
    container_name: identity-java.localhost
    build:
      context: ./identity-java
    environment:
      - "API_BASE_URL=http://api-go.localhost"
      - "API_BASE_URL_TLS=https://api-go.localhost"
      - "SPRING_PROFILES_ACTIVE=prod"
      - "CIPHER_IV="
      - "CIPHER_KEY="
      - "CIPHER_SALT="
      - "GITHUB_CLIENT_ID="
      - "GITHUB_CLIENT_SECRET="
      - "GITHUB_TOKEN_URL=https://github.com/login/oauth/access_token?client_id={client_id}&client_secret={client_secret}&code={code}"
      - "GITHUB_USER_INFO_URL=https://api.github.com/user"
      - "GITHUB_VALIDATION_URL=https://api.github.com/applications/{client_id}/tokens/{access_token}"
    ports:
      - "5432:5432"
    networks:
      - microservices-net

  api-go:
    container_name: api-go.localhost
    build:
      context: ./api-go
    environment: 
      - "SERVICE_PORT=80"
      - "CATALOG_BASE_URL=http://catalog-csharp.localhost"
      - "IDENTITY_BASE_URL=http://identity-java.localhost"
    networks: 
      - microservices-net
    depends_on: 
      - catalog-csharp
      - identity-java

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - microservices-net
    depends_on: 
      - catalog-csharp
      - web-nextjs
      - api-go
      - identity-java

networks: 
  microservices-net: 
    driver: bridge