version: "3"
services:
  web-nextjs:
    container_name: web-nextjs.localhost
    build:
      context: ./web-nextjs
    networks:
      - microservices-net
    depends_on:
      - catalog-csharp
      - api-go

  catalog-csharp:
    container_name: catalog-csharp.localhost
    build:
      context: ./catalog-csharp
    networks:
      - microservices-net

  api-go:
    container_name: api-go.localhost
    build:
      context: ./api-go
    environment: 
      - "SERVICE_PORT=80"
      - "CATALOG_BASE_URL=http://catalog-csharp"
    networks: 
      - microservices-net
    depends_on: 
      - catalog-csharp

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - microservices-net
    depends_on: 
      - catalog-csharp
      - web-nextjs
      - api-go

networks: 
  microservices-net: 
    driver: bridge