- name: Provisioning
  hosts: all
  become: true
  tasks:
  - name: Register Cassandra 3.1.1.x
    apt_repository:
      repo: deb http://www.apache.org/dist/cassandra/debian 311x main
      state: present
      filename: cassandra.sources.list

  - name: Add the Apache Cassandra repository keys
    apt_key:
      url: https://www.apache.org/dist/cassandra/KEYS
      state: present

  - name: Update apt packages
    apt:
      update_cache: yes

  - name: Install Cassandra package
    apt:
      name: cassandra
      state: present

  - name: Update Cassandra Authentication method
    replace:
      path: /etc/cassandra/cassandra.yaml
      regexp: 'AllowAllAuthenticator$'
      replace: 'PasswordAuthenticator'

  - name: Restart Cassandra
    service:
      name: cassandra
      state: restarted

  - name: Wait for Cassandra bootstrapping
    wait_for:
      path: /var/log/cassandra/system.log
      timeout: 60
      search_regex: "Created default superuser role 'cassandra'"

  - name: Verify Cassandra is running
    shell: nodetool status
    register: debugmsg

  - debug: msg="{{ debugmsg.stdout_lines }}"

  - name: Run seed script
    shell: cqlsh -u cassandra -p cassandra -f /provision/seed.cql