- name: Provisioning
  hosts: all
  become: true
  tasks:
  - name: Register Cassandra 3.1.1.x
    apt_repository:
      repo: deb http://www.apache.org/dist/cassandra/debian 311x main
      state: present
      filename: cassandra.sources.list

  - name: Add the Apache Cassandra repository keys
    apt_key:
      url: https://www.apache.org/dist/cassandra/KEYS
      state: present

  - name: Update apt packages
    apt:
      update_cache: yes

  - name: Uninstall Cassandra package
    apt:
      name: cassandra
      state: absent

  - name: Install Cassandra package
    apt:
      name: cassandra
      state: present

  - name: Update Cassandra Authentication method
    replace:
      path: /etc/cassandra/cassandra.yaml
      regexp: 'AllowAllAuthenticator$'
      replace: 'PasswordAuthenticator'

  - name: Rename cluster
    replace:
      path: /etc/cassandra/cassandra.yaml
      regexp: 'Test Cluster'
      replace: 'Ordering Cluster'

  - name: Set RPC server to enable
    replace:
      path: /etc/cassandra/cassandra.yaml
      regexp: '^start_rpc: false$'
      replace: 'start_rpc: true'

  - name: Set RPC address
    replace:
      path: /etc/cassandra/cassandra.yaml
      regexp: 'rpc_address: localhost$'
      replace: 'rpc_address: 0.0.0.0'

  - debug: msg="ip address {{ ansible_eth0.ipv4.address }}"

  - name: Set broadcast RPC address
    replace:
      path: /etc/cassandra/cassandra.yaml
      regexp: '^# broadcast_rpc_address: 1.2.3.4$'
      replace: 'broadcast_rpc_address: {{ ansible_eth0.ipv4.address }}'

  - name: Restart Cassandra
    service:
      name: cassandra
      state: restarted

  - name: Wait for Cassandra bootstrapping
    wait_for:
      path: /var/log/cassandra/system.log
      timeout: 60
      sleep: 5
      search_regex: "Created default superuser role 'cassandra'"

  - name: Verify Cassandra is running
    shell: nodetool status
    register: debugmsg

  - debug: msg="{{ debugmsg.stdout_lines }}"

  - name: Run seed script
    shell: cqlsh -u cassandra -p cassandra -f /provision/seed.cql