- name: Provisioning
  hosts: all
  become: true
  tasks:
  - name: Update apt packages
    apt:
      update_cache: yes

  - name: Uninstall Postgresql package
    apt:
      name: postgresql
      state: absent

  - name: Uninstall Postgresql contrib package
    apt:
      name: postgresql-contrib
      state: absent

  - name: Install Postgresql package
    apt:
      name: postgresql
      state: present

  - name: Install Postgresql contrib package
    apt:
      name: postgresql-contrib
      state: present

  - name: Create Postgresql role
    become: true
    become_user: postgres
    become_method: sudo
    command: psql -f /provision/seed.psql