- name: Provisioning
  hosts: all
  become: true
  tasks:
  - name: Import MS public repo GPG keys
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: Register MSSQL server 2017
    get_url:
      url: https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list
      dest: /etc/apt/sources.list.d/mssql.list

  - name: Register MSSQL tools
    get_url:
      url: https://packages.microsoft.com/config/ubuntu/16.04/prod.list
      dest: /etc/apt/sources.list.d/msprod.list

  - name: Update apt packages
    apt:
      update_cache: yes

  - name: Uninstall MSSQL server 2017 package
    apt:
      name: mssql-server
      state: absent

  - name: Install MSSQL server 2017 and tool package
    environment:
      ACCEPT_EULA: 'y'
    apt: 
      name: "{{ packages }}"
      allow_unauthenticated: yes
      force: yes
    vars:
      packages:
      - mssql-server
      - python-pexpect
      - mssql-tools

  - name: Setup MSSQL server 2017
    expect:
      echo: yes
      command: /opt/mssql/bin/mssql-conf setup
      responses:
        'Choose an edition of SQL Server': '3'
        'The license terms for this product': 'Y'
        'Enter the SQL Server': 'P@ssw0rd'
        'Confirm the SQL Server': 'P@ssw0rd'

  - name: Add {{extra_path}} to path
    lineinfile:
      path: /etc/environment
      state: present
      backrefs: yes
      regexp: 'PATH=(["]*)((?!.*?{{extra_path}}).*?)(["]*)$'
      line: 'PATH=\1\2:{{extra_path}}\3'
    vars:
      extra_path: /opt/mssql-tools/bin

  - name: Run seed script
    shell: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'P@ssw0rd' -i '/provision/seed.sql'